spring:
  h2:
    console:
      path: /console
  datasource:
    url: jdbc:h2:file:../db/links
    username: jeremi
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
